"""
risk_dashboard.py

Utilities for creating invoice risk dashboard summaries.

This module reads the generated invoice risk results and provides
summary statistics for the Streamlit dashboard.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


# ================================================================
# PATHS
# ================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

RESULTS_DIR = PROJECT_ROOT / "results"


# ================================================================
# LOAD RISK RESULTS
# ================================================================

def load_risk_results():
    """
    Load invoice risk results generated by the risk scoring pipeline.

    Returns
    -------
    pandas.DataFrame
        Risk results dataframe.
    """

    possible_files = [
        RESULTS_DIR / "invoice_risk_results.csv",
        RESULTS_DIR / "invoice_risk_summary.csv",
    ]

    for file_path in possible_files:

        if file_path.exists():

            try:

                df = pd.read_csv(
                    file_path
                )

                if not df.empty:

                    return df

            except Exception:
                continue

    return pd.DataFrame()


# ================================================================
# FIND COLUMN
# ================================================================

def find_column(
    df: pd.DataFrame,
    possible_names: list[str],
):
    """
    Find the first matching column from a list of possible names.
    """

    for name in possible_names:

        if name in df.columns:

            return name

    return None


# ================================================================
# NORMALIZE RISK LEVEL
# ================================================================

def normalize_risk_level(
    value,
):
    """
    Convert risk level values into standard categories.
    """

    if pd.isna(value):

        return "Unknown"

    text = str(
        value
    ).strip().lower()

    if text in [
        "low",
        "low risk",
    ]:

        return "Low"

    if text in [
        "medium",
        "moderate",
        "medium risk",
    ]:

        return "Medium"

    if text in [
        "high",
        "high risk",
        "critical",
    ]:

        return "High"

    return str(value)


# ================================================================
# PREPARE RISK DATA
# ================================================================

def prepare_risk_data(
    df: pd.DataFrame,
):
    """
    Prepare risk results for dashboard analysis.
    """

    if df.empty:

        return df.copy()

    result = df.copy()

    # ------------------------------------------------------------
    # FIND RISK SCORE
    # ------------------------------------------------------------

    risk_score_column = find_column(
        result,
        [
            "risk_score",
            "RiskScore",
            "final_risk_score",
            "risk",
        ],
    )

    if risk_score_column is not None:

        result[
            "dashboard_risk_score"
        ] = pd.to_numeric(
            result[
                risk_score_column
            ],
            errors="coerce",
        )

    else:

        result[
            "dashboard_risk_score"
        ] = np.nan

    # ------------------------------------------------------------
    # FIND RISK LEVEL
    # ------------------------------------------------------------

    risk_level_column = find_column(
        result,
        [
            "risk_level",
            "RiskLevel",
            "risk_category",
            "RiskCategory",
        ],
    )

    if risk_level_column is not None:

        result[
            "dashboard_risk_level"
        ] = result[
            risk_level_column
        ].apply(
            normalize_risk_level
        )

    else:

        # --------------------------------------------------------
        # CREATE RISK LEVEL FROM SCORE
        # --------------------------------------------------------

        def score_to_level(
            score,
        ):

            if pd.isna(score):

                return "Unknown"

            if score < 30:

                return "Low"

            if score < 70:

                return "Medium"

            return "High"

        result[
            "dashboard_risk_level"
        ] = result[
            "dashboard_risk_score"
        ].apply(
            score_to_level
        )

    return result


# ================================================================
# RISK SUMMARY
# ================================================================

def calculate_risk_summary(
    df: pd.DataFrame,
):
    """
    Calculate overall risk dashboard statistics.
    """

    if df.empty:

        return {
            "total_invoices": 0,
            "low_risk": 0,
            "medium_risk": 0,
            "high_risk": 0,
            "unknown_risk": 0,
            "average_risk_score": 0.0,
            "high_risk_percentage": 0.0,
            "medium_high_percentage": 0.0,
        }

    prepared = prepare_risk_data(
        df
    )

    total = len(
        prepared
    )

    low_count = int(
        (
            prepared[
                "dashboard_risk_level"
            ]
            == "Low"
        ).sum()
    )

    medium_count = int(
        (
            prepared[
                "dashboard_risk_level"
            ]
            == "Medium"
        ).sum()
    )

    high_count = int(
        (
            prepared[
                "dashboard_risk_level"
            ]
            == "High"
        ).sum()
    )

    unknown_count = int(
        (
            prepared[
                "dashboard_risk_level"
            ]
            == "Unknown"
        ).sum()
    )

    average_score = (
        prepared[
            "dashboard_risk_score"
        ]
        .mean()
    )

    if pd.isna(
        average_score
    ):

        average_score = 0.0

    high_percentage = (
        high_count
        /
        total
        *
        100
        if total > 0
        else 0
    )

    medium_high_percentage = (
        (
            medium_count
            +
            high_count
        )
        /
        total
        *
        100
        if total > 0
        else 0
    )

    return {
        "total_invoices": total,
        "low_risk": low_count,
        "medium_risk": medium_count,
        "high_risk": high_count,
        "unknown_risk": unknown_count,
        "average_risk_score": float(
            average_score
        ),
        "high_risk_percentage": float(
            high_percentage
        ),
        "medium_high_percentage": float(
            medium_high_percentage
        ),
    }


# ================================================================
# RISK DISTRIBUTION
# ================================================================

def get_risk_distribution(
    df: pd.DataFrame,
):
    """
    Return risk-level counts suitable for charting.
    """

    summary = calculate_risk_summary(
        df
    )

    return pd.DataFrame(
        {
            "Risk Level": [
                "Low",
                "Medium",
                "High",
            ],
            "Invoices": [
                summary[
                    "low_risk"
                ],
                summary[
                    "medium_risk"
                ],
                summary[
                    "high_risk"
                ],
            ],
        }
    )


# ================================================================
# TOP RISKY INVOICES
# ================================================================

def get_top_risky_invoices(
    df: pd.DataFrame,
    limit: int = 10,
):
    """
    Return invoices with the highest risk scores.
    """

    if df.empty:

        return pd.DataFrame()

    prepared = prepare_risk_data(
        df
    )

    sorted_df = (
        prepared
        .sort_values(
            "dashboard_risk_score",
            ascending=False,
            na_position="last",
        )
        .head(limit)
        .copy()
    )

    display_columns = []

    possible_columns = [
        "PONumber",
        "VendorNumber",
        "VendorName",
        "InvoiceDate",
        "invoice_dollars",
        "Freight",
        "dashboard_risk_score",
        "dashboard_risk_level",
        "anomaly_score",
    ]

    for column in possible_columns:

        if column in sorted_df.columns:

            display_columns.append(
                column
            )

    result = sorted_df[
        display_columns
    ].copy()

    if (
        "dashboard_risk_score"
        in result.columns
    ):

        result[
            "dashboard_risk_score"
        ] = result[
            "dashboard_risk_score"
        ].round(2)

    return result


# ================================================================
# TOP RISKY VENDORS
# ================================================================

def get_top_risky_vendors(
    df: pd.DataFrame,
    limit: int = 10,
):
    """
    Calculate vendor-level risk statistics.
    """

    if df.empty:

        return pd.DataFrame()

    prepared = prepare_risk_data(
        df
    )

    vendor_column = find_column(
        prepared,
        [
            "VendorName",
            "vendor_name",
            "Vendor",
        ],
    )

    if vendor_column is None:

        return pd.DataFrame()

    vendor_result = (
        prepared
        .groupby(
            vendor_column,
            dropna=False,
        )
        .agg(
            invoice_count=(
                "dashboard_risk_score",
                "count",
            ),
            average_risk_score=(
                "dashboard_risk_score",
                "mean",
            ),
            maximum_risk_score=(
                "dashboard_risk_score",
                "max",
            ),
            high_risk_invoices=(
                "dashboard_risk_level",
                lambda x: (
                    x == "High"
                ).sum(),
            ),
            medium_risk_invoices=(
                "dashboard_risk_level",
                lambda x: (
                    x == "Medium"
                ).sum(),
            ),
        )
        .reset_index()
    )

    vendor_result = (
        vendor_result
        .sort_values(
            [
                "high_risk_invoices",
                "average_risk_score",
            ],
            ascending=False,
        )
        .head(limit)
    )

    vendor_result[
        "average_risk_score"
    ] = vendor_result[
        "average_risk_score"
    ].round(2)

    vendor_result[
        "maximum_risk_score"
    ] = vendor_result[
        "maximum_risk_score"
    ].round(2)

    return vendor_result


# ================================================================
# ANOMALY SUMMARY
# ================================================================

def calculate_anomaly_summary(
    df: pd.DataFrame,
):
    """
    Calculate anomaly statistics from risk results.
    """

    if df.empty:

        return {
            "analyzed": 0,
            "anomalies": 0,
            "anomaly_percentage": 0.0,
        }

    anomaly_column = find_column(
        df,
        [
            "anomaly_status",
            "AnomalyStatus",
            "is_anomaly",
        ],
    )

    if anomaly_column is None:

        return {
            "analyzed": len(df),
            "anomalies": 0,
            "anomaly_percentage": 0.0,
        }

    values = (
        df[
            anomaly_column
        ]
        .astype(str)
        .str.lower()
        .str.strip()
    )

    anomaly_count = int(
        values.isin(
            [
                "anomaly",
                "true",
                "1",
                "yes",
            ]
        ).sum()
    )

    total = len(
        df
    )

    percentage = (
        anomaly_count
        /
        total
        *
        100
        if total > 0
        else 0
    )

    return {
        "analyzed": total,
        "anomalies": anomaly_count,
        "anomaly_percentage": float(
            percentage
        ),
    }


# ================================================================
# EXPORT
# ================================================================

__all__ = [
    "load_risk_results",
    "prepare_risk_data",
    "calculate_risk_summary",
    "get_risk_distribution",
    "get_top_risky_invoices",
    "get_top_risky_vendors",
    "calculate_anomaly_summary",
]